version: '3'

networks:
  ecommerce:
    driver: bridge

services:
  db:
    image: bungdanar/ecommerce-mysql
    restart: 'no'
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    networks:
      - ecommerce

  webapi:
    image: bungdanar/ecommerce-webapi
    depends_on:
      - db
    restart: 'no'
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    env_file:
      - .env
    networks:
      - ecommerce
    ports:
      - '${PORT}:${PORT}'
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm run start:prod'
